# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-08 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20171208_1551'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='suser',
        ),
    ]
