# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-08 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20171208_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ssuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='suser',
        ),
    ]
