# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-09 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_ssuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ssuser',
        ),
    ]
