# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-23 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='aaaaaaaa', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='au_id',
            field=models.DecimalField(decimal_places=0, default='0000000', max_digits=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='flag',
            field=models.DecimalField(decimal_places=0, default='00', max_digits=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_no',
            field=models.DecimalField(decimal_places=0, default='1234567890', max_digits=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='hello', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(default='hello@hello.com', max_length=250),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='hello123', max_length=250),
        ),
    ]
