# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-23 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20171223_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='cname',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='a', max_length=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='au_id',
            field=models.DecimalField(decimal_places=0, default='a', max_digits=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(default='a', max_length=250),
        ),
        migrations.AlterField(
            model_name='customer',
            name='flag',
            field=models.DecimalField(decimal_places=0, default='a', max_digits=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_no',
            field=models.DecimalField(decimal_places=0, default='a', max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='a', max_length=250),
        ),
    ]
