# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-05 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_customer_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user_type',
        ),
    ]
