# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-21 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_remove_customer_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='a', max_length=250)),
                ('password', models.CharField(default='a', max_length=250)),
                ('au_id', models.DecimalField(decimal_places=0, default='a', max_digits=200)),
                ('flag', models.DecimalField(decimal_places=0, default='a', max_digits=2)),
            ],
        ),
    ]
