# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-21 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='myadmin',
        ),
    ]
