# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-21 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20180121_1450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myadmintable',
        ),
    ]
