# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-18 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_myadmintable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myadmintable',
        ),
    ]
