# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-18 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_delete_myadmintable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='au_id',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cflag',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
