# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-25 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20180218_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='a', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='au_id',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cflag',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cname',
            field=models.CharField(blank=True, default='a', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, default='a', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_no',
            field=models.DecimalField(blank=True, decimal_places=0, default='a', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, default='a', max_length=250, null=True),
        ),
    ]
