# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-23 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0009_auto_20171223_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('mobile', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cm_msg', models.CharField(max_length=1000)),
                ('flag', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('mobile', models.DecimalField(decimal_places=0, max_digits=10)),
                ('f_msg', models.CharField(max_length=1000)),
                ('flag', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.DecimalField(decimal_places=0, max_digits=2)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.customer')),
            ],
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=100)),
                ('transaction_id', models.DecimalField(decimal_places=0, max_digits=150)),
                ('flag', models.DecimalField(decimal_places=0, max_digits=2)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.customer')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=250)),
                ('au_id', models.DecimalField(decimal_places=0, max_digits=20)),
                ('pro_price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('prodct_dec', models.CharField(max_length=1000)),
                ('flag', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='retail_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=100)),
                ('flag', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=3)),
                ('flag', models.DecimalField(decimal_places=0, max_digits=2)),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.product')),
            ],
        ),
        migrations.CreateModel(
            name='temp_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=50)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=100)),
                ('flag', models.DecimalField(decimal_places=0, max_digits=2)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.customer')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.product')),
            ],
        ),
        migrations.CreateModel(
            name='warehouse_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=3)),
                ('flag', models.DecimalField(decimal_places=0, max_digits=2)),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.stock')),
            ],
        ),
        migrations.AddField(
            model_name='retail_stock',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.stock'),
        ),
        migrations.AddField(
            model_name='payments',
            name='tc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.temp_cart'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='pay_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.payments'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='tc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.temp_cart'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='o_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.order_details'),
        ),
    ]
