# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-20 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_auto_20180218_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(default='a', max_length=100)),
                ('email', models.CharField(default='a', max_length=250)),
                ('password', models.CharField(default='a', max_length=250)),
                ('mobile_no', models.DecimalField(decimal_places=0, default='a', max_digits=10)),
                ('address', models.CharField(default='a', max_length=500)),
                ('au_id', models.DecimalField(decimal_places=0, default=0, max_digits=200)),
                ('cflag', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
            ],
        ),
    ]
