# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-20 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_delete_customer2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
