# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-21 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_delete_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retail_stock',
            name='s_id',
        ),
        migrations.RemoveField(
            model_name='warehouse_stock',
            name='s_id',
        ),
        migrations.DeleteModel(
            name='retail_stock',
        ),
        migrations.DeleteModel(
            name='warehouse_stock',
        ),
    ]
