# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-21 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_auto_20180221_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='tc_id',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='tc_id',
        ),
        migrations.RemoveField(
            model_name='temp_cart',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='order_details',
            name='products',
            field=models.CharField(default='a', max_length=250),
        ),
        migrations.AddField(
            model_name='order_details',
            name='quantity',
            field=models.CharField(default='a', max_length=250),
        ),
    ]
