# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-21 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_auto_20180221_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='cm_msg',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='replay',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='products',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='quantity',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
