# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-21 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0010_auto_20180221_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='myadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='a', max_length=250)),
                ('password', models.CharField(default='a', max_length=250)),
            ],
        ),
    ]
