# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-23 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0011_myadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='pay_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='myadmin.payments'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.DecimalField(decimal_places=0, max_digits=150, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_primary', to='myadmin.product'),
        ),
    ]
