# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-07 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0014_auto_20180225_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='c_id',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.customer'),
        ),
    ]
