# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-11 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0015_auto_20180307_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.BinaryField(blank=True),
        ),
    ]
