# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-11 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0018_auto_20180311_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.BinaryField(blank=True),
        ),
    ]
